---
title: "Получение сведений о системе"
author: Лаптинский Дмитрий
format: html
editor: visual
---

**\# Получение сведений о системе**

\
**\## Цель работы**\
Получить сведения об используемой системе\
**\## Исходные данные**\
1. Ноутбук Asus\
2. Ubuntu 22.04.2 LTS\
3. Интерпретатор командной оболочки bash 5.2.15\
4. Эмулятор терминала Konsole\
**\## План**\
1. Ввод команд в эмулятор терминала\
2. Анализ данных\
**\## Ход работы**\
1. Для начала получим сведения об используемом дистрибутиве:\
\`\`\`dmitry@dmitry-VirtualBox:\~\$ lsb_release -aNo LSB modules are available.Distributor ID: UbuntuDescription: Ubuntu 22.04.2 LTSRelease: 22.04Codename: jammy\`\`\`\
В результате выполнения данной команды было определён используемый дистрибутив - Ubuntu 22.04.2 LTS.\
2.Затем получим сведения о версии ядра:\
\`\`\`dmitry@dmitry-VirtualBox:\~\$ uname -aLinux dmitry-VirtualBox 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux\`\`\`\
В результате выполнения данной команды была получена версия ядра - 5.19.0-35, дата компиляции ядра - Fri Feb 17 15:17:25.\
3.Далее можно получить сведения о процессоре:\
\`\`\`dmitry@dmitry-VirtualBox:~$ cat /proc/cpuinfo | grep "model name" model name : 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz model name : 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz model name : 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz model name : 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz model name : 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz model name : 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz\`\`\`\
Было определено, что используемый процессор - шестипоточный Intel(R) Core(TM) i5-11400H с тактовой частотой 2.7ГГц.\
4.Далее получим последние 30 строк логов системы:\
\`\`\`dmitry@dmitry-VirtualBox:~$ journalctl -q -b| tail -n 30 мар 02 16:20:50 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11). мар 02 16:20:52 dmitry-VirtualBox gnome-shell[1326]: Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12). мар 02 16:21:16 dmitry-VirtualBox systemd[1170]: gnome-terminal-server.service: Consumed 2.995s CPU time. мар 02 16:21:18 dmitry-VirtualBox systemd[1170]: Started Application launched by gnome-shell. мар 02 16:21:18 dmitry-VirtualBox dbus-daemon[1205]: [session uid=1000 pid=1205] Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service' requested by ':1.113' (uid=1000 pid=2593 comm="/usr/bin/gnome-terminal.real " label="unconfined") мар 02 16:21:18 dmitry-VirtualBox systemd[1170]: Starting GNOME Terminal Server... мар 02 16:21:19 dmitry-VirtualBox dbus-daemon[1205]: [session uid=1000 pid=1205] Successfully activated service 'org.gnome.Terminal' мар 02 16:21:19 dmitry-VirtualBox systemd[1170]: Started GNOME Terminal Server. мар 02 16:21:19 dmitry-VirtualBox systemd[1170]: Started VTE child process 2624 launched by gnome-terminal-server process 2598. мар 02 16:24:11 dmitry-VirtualBox anacron[659]: Job `cron.weekly' started мар 02 16:24:11 dmitry-VirtualBox anacron[2647]: Updated timestamp for job `cron.weekly' to 2023-03-02 мар 02 16:24:11 dmitry-VirtualBox anacron[659]: Job `cron.weekly' terminated мар 02 16:24:13 dmitry-VirtualBox snapd[682]: devicemgr.go:2300: no NTP sync after 10m0s, trying auto-refresh anyway мар 02 16:29:11 dmitry-VirtualBox anacron[659]: Job `cron.monthly' started мар 02 16:29:11 dmitry-VirtualBox systemd[1]: Starting Cleanup of Temporary Directories... мар 02 16:29:11 dmitry-VirtualBox anacron[659]: Job `cron.monthly' terminated мар 02 16:29:11 dmitry-VirtualBox anacron[659]: Normal exit (2 jobs run) мар 02 16:29:11 dmitry-VirtualBox anacron[2660]: Updated timestamp for job `cron.monthly' to 2023-03-02 мар 02 16:29:11 dmitry-VirtualBox systemd[1]: anacron.service: Killing process 2660 (anacron) with signal SIGKILL. мар 02 16:29:11 dmitry-VirtualBox systemd[1]: anacron.service: Deactivated successfully. мар 02 16:29:11 dmitry-VirtualBox systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully. мар 02 16:29:11 dmitry-VirtualBox systemd[1]: Finished Cleanup of Temporary Directories.\`\`\`\
**\## Оценка результата**\
В результате лабораторной работы была получена базовая информация об используемой системе.\
**\## Вывод**\
Таким образом. мы научились, используя команды Linux, получать сведения о системе.\
